# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_create_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.IntegerField()),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Trial')),
            ],
        ),
    ]
