# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_create_study'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.AlterField(
            model_name='study',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
