# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_create_marking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='dob',
        ),
    ]
